version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - ng lint
      - ng test core
      - ng test darknesing
      - ng build darknesing --prod
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
