version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - ng lint
      - ng test core
      - ng test darknesing
      - ng build darknesing --prod
  post_build:
    commands:
      - aws s3 rm s3://${S3_BUCKET} --recursive
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
