steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'install' ]

  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run', 'lint' ]
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run', 'test', 'core' ]
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run', 'test', 'darknesing' ]

  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run', 'build', 'darknesing', '--prod' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'app', 'deploy', '--version=prod' ]
timeout: "1600s"
